# This file contains configuration for parsing, preprocessing and analyzing
# the raw data obtained from baseline and multi-task experiments.

# baselines:
#   experiment: truemin-source (index 0: sobol runs, 1: boss runs)
baselines:
  2LFbasic0: 2LFbasic1
  2LFbasic1: 2LFbasic1
  2HFbasic0: 2HFbasic1
  2HFbasic1: 2HFbasic1
  2UHFbasic0: 2UHFbasic1
  2UHFbasic1: 2UHFbasic1
  2UHFbasic1_r: 2UHFbasic1_r
  4LFbasic0_sobol: 4LFbasic1
  4LFbasic0: 4LFbasic1
  4LFbasic1: 4LFbasic1
  4HFbasic0_sobol: 4HFbasic1
  4HFbasic0: 4HFbasic1
  4HFbasic1: 4HFbasic1
  4UHFbasic1_r: 4UHFbasic1_r


# TL_experiments:
#   experiment:
#     - [primary task, init. method]
#     - [secondary task, init. method]
experiments:
  2HF_ICM1_ELCB1:
    - [2HFbasic1, random]
    - [2LFbasic1, inorder]
  2HF_ICM1_ELCB3:
    - [2HFbasic1, random]
    - [2LFbasic1, inorder]
  2HF_ICM1_ELCB6:
    - [2HFbasic1, random]
    - [2LFbasic1, inorder]
  2UHF_ICM1_ELCB1:
    - [2UHFbasic1_r, random]
    - [2LFbasic1, inorder]
  2UHF_ICM1_ELCB3:
    - [2UHFbasic1_r, random]
    - [2LFbasic1, inorder]
  2UHF_ICM1_ELCB6:
    - [2UHFbasic1_r, random]
    - [2LFbasic1, inorder]
  2UHF_ICM2_ELCB1:
    - [2UHFbasic1_r, random]
    - [2LFbasic1, inorder]
  2UHF_ICM2_ELCB3:
    - [2UHFbasic1_r, random]
    - [2LFbasic1, inorder]
  2UHF_ICM2_ELCB6:
    - [2UHFbasic1_r, random]
    - [2LFbasic1, inorder]
  4HF_ICM1_ELCB1:
    - [4HFbasic1, random]
    - [4LFbasic1, inorder]
  4HF_ICM1_ELCB3:
    - [4HFbasic1, random]
    - [4LFbasic1, inorder]
  4HF_ICM1_ELCB6:
    - [4HFbasic1, random]
    - [4LFbasic1, inorder]
  4UHF_ICM1_ELCB1:
    - [4UHFbasic1_r, random]
    - [4LFbasic1, inorder]
  4UHF_ICM1_ELCB3:
    - [4UHFbasic1_r, random]
    - [4LFbasic1, inorder]
  4UHF_ICM1_ELCB6:
    - [4UHFbasic1_r, random]
    - [4LFbasic1, inorder]
  4UHF_ICM2_ELCB1:
    - [4UHFbasic1_r, random]
    - [4LFbasic1, inorder]
  4UHF_ICM2_ELCB3:
    - [4UHFbasic1_r, random]
    - [4LFbasic1, inorder]
  4UHF_ICM2_ELCB6:
    - [4UHFbasic1_r, random]
    - [4LFbasic1, inorder]

# Tolerances levels for convergence in units of kcal/mol.
tolerances: [5, 2, 1, 0.5, 0.23, 0.2, 0.1, 0.05, 0.02, 0.01, 0.005, 0.002, 0.001]

# MT experiment_plots:
#   experiment: [primary task, secondary task]
MT_experiment_plots_2D:
  2HF_ICM1_ELCB1: [2HFbasic1, 2LFbasic1]
  2HF_ICM1_ELCB3: [2HFbasic1, 2LFbasic1]
  2HF_ICM1_ELCB6: [2HFbasic1, 2LFbasic1]
  2UHF_ICM1_ELCB1: [2UHFbasic1_r, 2LFbasic1]
  2UHF_ICM1_ELCB3: [2UHFbasic1_r, 2LFbasic1]
  2UHF_ICM1_ELCB6: [2UHFbasic1_r, 2LFbasic1]
  2UHF_ICM2_ELCB1: [2UHFbasic1_r, 2LFbasic1]
  2UHF_ICM2_ELCB3: [2UHFbasic1_r, 2LFbasic1]
  2UHF_ICM2_ELCB6: [2UHFbasic1_r, 2LFbasic1]

MT_experiment_plots_4D:
  4HF_ICM1_ELCB1: [4HFbasic1, 4LFbasic1]
  4HF_ICM1_ELCB3: [4HFbasic1, 4LFbasic1]
  4HF_ICM1_ELCB6: [4HFbasic1, 4LFbasic1]
  4UHF_ICM1_ELCB1: [4UHFbasic1_r, 4LFbasic1]
  4UHF_ICM1_ELCB3: [4UHFbasic1_r, 4LFbasic1]
  4UHF_ICM1_ELCB6: [4UHFbasic1_r, 4LFbasic1]
  4UHF_ICM2_ELCB1: [4UHFbasic1_r, 4LFbasic1]
  4UHF_ICM2_ELCB3: [4UHFbasic1_r, 4LFbasic1]
  4UHF_ICM2_ELCB6: [4UHFbasic1_r, 4LFbasic1]
