# This file contains configuration for parsing, preprocessing and analyzing
# the raw data obtained from baseline and transfer learning exeperiments.

# baselines:
#   experiment: truemin-source (index 0: sobol runs, 1: boss runs)
baselines:
  2LFbasic0: 2LFbasic1
  2LFbasic1: 2LFbasic1
  2HFbasic0: 2HFbasic1
  2HFbasic1: 2HFbasic1
  2UHFbasic0: 2UHFbasic1
  2UHFbasic1: 2UHFbasic1
  2UHFbasic1_r: 2UHFbasic1_r
  4LFbasic0_sobol: 4LFbasic1
  4LFbasic1: 4LFbasic1
  4HFbasic0_sobol: 4HFbasic1
  4HFbasic1: 4HFbasic1
  4UHFbasic1_r: 4UHFbasic1_r

# TL_experiments:
#   experiment:
#     - [primary task, init. method]
#     - [secondary task, init. method]
TL_experiments:
  2UHFICM1:
    - [2UHFbasic1_r, random]
    - [2LFbasic1, inorder]
  2UHFICM2:
    - [2UHFbasic1_r, random]
    - [2HFbasic1, inorder]
  2HFICM1:
    - [2HFbasic1, random]
    - [2LFbasic1, inorder]

# Tolerances levels for convergence. For TL, only 0.1 kcal/mol is used
tolerances: [5, 2, 1, 0.5, 0.2, 0.1, 0.05, 0.02, 0.01, 0.005, 0.002, 0.001]

# List of sobol runs
sobol:
  - '2UHFbasic0'
  - '2HFbasic0'
  - '2LFbasic0'

# TL experiment_plots:
#   experiment: [primary task, secondary task]
TL_experiment_plots:
  2HFICM1: [2HFbasic1, 2LFbasic1]
  2UHFICM1: [2UHFbasic1_r, 2LFbasic1]
  2UHFICM2: [2UHFbasic1_r, 2HFbasic1]
