# This file contains configuration for parsing, preprocessing and analyzing
# the raw data obtained from baseline and transfer learning experiments.

# baselines:
#   experiment: truemin-source (index 0: sobol runs, 1: boss runs)
baselines:
  a1a3: a1a3
  a1b2: a1b2
  b1a2: b1a2
  b1b2: b1b2

# TL_experiments:
#   experiment:
#     - [primary task, init. method]
#     - [secondary task, init. method]
TL_experiments:
  # 2UHFICM1:
  #   - [2UHFbasic1_r, random]
  #   - [2LFbasic1, inorder]
  MT_a3b7:
    - [a1b2, random]
    - [a1a3, inorder]
  MT_b3b1:
    - [b1b2, random]
    - [b1a2, inorder]

# TL experiment_plots:
#   experiment: [primary task, secondary task]
TL_experiment_plots_2D:
 MT_a3b7: [a1b2, a1a3]
TL_experiment_plots_4D:
  MT_b3b1: [b1b2, b1a2]

# Tolerances levels for convergence in units of kcal/mol.
tolerances: [5, 2, 1, 0.5, 0.2, 0.1, 0.05, 0.02, 0.01, 0.005, 0.002, 0.001]
